<?php 
// visit : https://crackstation.net/  to craack md5 hashes
if($_POST)     //
{
    if(array_key_exists("password",$_POST))
    {
        $id=1;   //id of user
        $salt = md5($id);     //md5 of id
        $hashVal = md5($salt."password");    //md5 of ((md5 of id).inputPasswod);   //to make it more secure.
        echo $hashVal."<br>";
        if($hashVal == md5($salt.$_POST["password"]))
        {
            echo "Yes my password is ".$_POST["password"]."<br>";
        }
        else
        {
            echo "No that's not my password. :)<br>";   
        }
    }

    if(array_key_exists("password2",$_POST))
    {
        echo md5($_POST["password2"])."<br>";
        $hashVal =md5("password");
        if($hashVal == md5($_POST["password2"]))
        {
            echo "Yes my password is ".$_POST["password2"]."<br>";
        }
        else
        {
            echo "No that's not my password. <br>";   
        }
    }

}



?>


<!-- strong hash generated from this form. can't easily be cracked. -->
<form method="post">
    <h1>What is my password?</h1>
    <label for="password">Password: </label>
    <input type="password" name="password" id="password"/>
    <br>
    <input type="submit" value="Check"/>
</form>

<hr>

<!-- hash generated by this form can easily be cracked for weak passwords from https://crackstation.net/ -->
<form method="post">      
    <h1>What is my password?</h1>
    <label for="password2">Password: </label>
    <input type="password" name="password2" id="password2"/>
    <br>
    <input type="submit" value="Check"/>
</form>
